version: '3.4'
services:
  shule:
    image: shule
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ENV: production
    ports:
      - 8080:38080
      - 9229:9229
