version: '3.4'
services:
  shule:
    image: shule
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CI_ENV: production
    ports:
      - 3080:3080
      - 9229:9229
